// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2ydhNDG_9r5UY421T5aL-X8ku7m8uxU',
    appId: '1:155927804620:android:a3dbbf8ea9cde61ba26069',
    messagingSenderId: '155927804620',
    projectId: 'numbers-b8a0e',
    storageBucket: 'numbers-b8a0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD42oOvk4viWUOKk5qFXIyV1VgB3BJZh8E',
    appId: '1:155927804620:ios:6fb3fbad272c971ba26069',
    messagingSenderId: '155927804620',
    projectId: 'numbers-b8a0e',
    storageBucket: 'numbers-b8a0e.appspot.com',
    iosClientId: '155927804620-on84p8hujmkjf69fsf32fpat0hr2ramn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
